[package]
name = "kz-util"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.10.3"
rand = "0.8.5"
decorum = { version = "0.3.1", default-features = false, features = ["std"] }
num-traits = "0.2.14"