[package]
name = "knpy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "knpy"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
kn-graph.workspace = true
kn-cuda-eval.workspace = true
