[workspace]

members = [
    "cuda-sys",
    "cuda-nn-eval",
    "alpha-zero",
]

[profile.release]
# lto = true
debug = true

[profile.dev]
opt-level = 1

# temporary fix until https://github.com/jordanbray/chess/pull/67 is merged
[profile.dev.build-override]
opt-level = 3
[profile.release.build-override]
opt-level = 3
[profile.test.build-override]
opt-level = 3