[package]
name = "sttt-zero"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sttt = { path = "../../SuperTTTApi-rs" }

crossbeam = "0.8.0"
itertools = "0.10.0"
num_cpus = "1.13.0"
ordered-float = "2.2.0"
rand = "0.8.3"
rayon = "1.5.0"
static_assertions = "1.1.0"
tch = "0.4.1"
torch-sys = "0.4.1"
ta = "0.4.0"
closure = "0.3.0"
onnxruntime = "0.0.12"
ndarray = "0.15.3"
rental = "0.5.6"

[profile.release]
debug = true

[profile.dev]
opt-level = 1
