[package]
name = "sttt-zero"
version = "0.1.0"
edition = "2018"

[features]
default = ["torch"]

onnx = ["onnxruntime"]
torch = ["tch"]

[dependencies]
sttt = { path = "../../SuperTTTApi-rs" }

tch = { version = "0.4.1", optional = true }
onnxruntime = { version = "0.0.12", optional = true }

num_cpus = "1.13.0"
crossbeam = "0.8.0"
rayon = "1.5.0"
itertools = "0.10.0"
rand = "0.8.3"
ordered-float = "2.2.0"
static_assertions = "1.1.0"
ta = "0.4.0"
closure = "0.3.0"
self_cell = "0.9.0"
rand_distr = "0.4.1"

[profile.release]
debug = true

[profile.dev]
opt-level = 1
