[package]
name = "cuda-nn-eval"
version = "0.1.0"
edition = "2018"

[dependencies]
cuda-sys = { path = "../cuda-sys" }
nn-graph = { path = "../nn-graph" }

bytemuck = "1.7.2"
itertools = "0.10.1"
rand = "0.8.4"

[dev-dependencies]
criterion = "0.3"

[build-dependencies]
cc = "1.0.71"

[[bench]]
name = "memory"
harness = false