[package]
name = "alpha-zero"
description = "Implementation of AlphaZero, including selfplay game generation"
version = "0.2.0"
edition = "2018"

[features]
default = ["tch", "onnxruntime"]

[dependencies]
board-game = { path = "../board-game" }

# TODO update to 0.5.0, but cl compiler error
tch = { version = "0.4.1", optional = true }
onnxruntime = { version = "0.0.14", optional = true }
cuda-nn-eval = { path = "../cuda-nn-eval" }
cuda-sys = { path = "../cuda-sys" }

num_cpus = "1.13.0"
crossbeam = "0.8.1"
rayon = "1.5.1"
itertools = "0.10.1"
rand = "0.8.4"
ta = "0.5.0"
self_cell = "0.9.0"
rand_distr = "0.4.1"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
decorum = { version = "0.3.1", default-features = false, features = ["std"] }
internal-iterator = "0.1.2"
safe-transmute = "0.11.2"
image = "0.23.14"
anyhow = "1.0.42"
lru = "0.6.6"
